name: "HCL AppScan Source Action"
on:
  workflow_dispatch
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run AppScan Source scan
        uses: coadaflorin/source-action@10.0.8
        with:
          script-file: source-cli.script
        env:
            AS_LICENSE_TYPE: 'CLS'
            AS_LICENSE_SERVER_ID: ${{secrets.SERVER_ID}}
            AS_LICENSE_SERVER: ${{secrets.LICENSE_SERVER}}
            AS_INSTALL_MODE: 'standalone'
      - name: Archive scan results
        uses: actions/upload-artifact@v3
        with:
          name: appscan-source-results
          path: |
            .appscan_source/docker_scan_altoroJ.ozasmt
            .appscan_source/scan_report.pdf
            
